# Generated by Django 4.2.13 on 2024-06-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attractions_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='linenos',
        ),
    ]
